version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: test-mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped
    
  lora-gateway-logger:
    build: .
    container_name: lora-gateway-logger-test
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_PORT=1883
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped